### ISSUE TITLE
My Portfolio Could not be deployed to github pages...

### ISSUE THREAD

**Issue by wasifkhan00** [RiadhAdrani/slick-portfolio-svelte#53] opened 2024-10-24 19:11 UTC
Hey Riadh,
I hope you are doing well, I'm facing issues regarding the deployment of this forked repo for my portfolio. I have followed the instructions as instructed in Readme.md. I have made changes to the deploy.yml and svelte.config.js but all in vain and I am unable to host my repo.  Could you please help me regarding that?

Link to Repository.[Repo](https://github.com/wasifkhan00/wasif-khan-port)

Edited: I have already gone through the existing closed issues and the new updated readme still couldn't figure it out. Also the updated Readme file. When I click on site link it only shows me Readme file.

![site link](https://github.com/user-attachments/assets/f1850ced-85dc-46ed-a54c-cba0a5bc42a0)

Thank You in Advance Riyadh!

**Comment by RiadhAdrani** [comment] 2024-10-24 21:14
Hey @wasifkhan00 ,
I created a pull request on your repo, hopefully resolving the issue with deployment to github pages.
Let me know if the problem is fixed.

**Comment by wasifkhan00** [comment] 2024-10-24 21:54
Hey @RiadhAdrani,
Thank you so much for helping me out it worked, that's silly of me for not checking the package.json file. Thank you again i really appreciate you for helping me out 🙏😊.

**Closed as completed** 2024-10-24 21:54 UTC
